version: '3.8'

services:
  rd-manpower-tool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rd-manpower-tool
    restart: unless-stopped
    ports:
      - "8080:80"  # 可以修改为你需要的端口
    environment:
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx  # 日志映射到本地
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge 